### ISSUE TITLE
Problems with quad(Forward+ Sample)

### ISSUE THREAD

**Issue by galek** [asylum2010/Asylum_Tutorials#1]
Hi

I think,what you forgot make:

``` C++
                glActiveTexture(GL_TEXTURE0 + tex_unit);
before
                glBindTexture(GL_TEXTURE_2D, framebuffer->GetColorAttachment(tex_unit));
and
                glBindTexture(GL_TEXTURE_2D, 0);
```

because we can get black screen

Correct version for me(this fragment is correct for OGL4(http://docs.gl/gl4/glActiveTexture))

``` C++
        void GLFBO::BindColorTexture(size_t tex_unit)
        {
                glActiveTexture(GL_TEXTURE0 + tex_unit);
                glBindTexture(GL_TEXTURE_2D, this->GetColorAttachment(tex_unit));
        }

        void GLFBO::UnBindActiveTexture(size_t tex_unit)
        {
                glActiveTexture(GL_TEXTURE0 + tex_unit);
                glBindTexture(GL_TEXTURE_2D, 0);
        }
```

**Comment by asylum2010** [comment]
Hi,

yes it might be safer, but I didn't forget it, I just know that GL_TEXTURE0
is active at that point (see line 812).

A more general solution would be to decouple the framebuffer and texture
completely:

void GraphicsDevice::SetRenderTarget(Renderable\* fbo)
{
    // ...
    glBindFramebuffer(GL_FRAMEBUFFER, fbo->GetID());
}

void GraphicsDevice::SetTexture(int unit, Texture\* tex)
{
    // ...
    glActiveTexture(GL_TEXTURE0 + unit);
    glBindTexture(GL_TEXTURE_2D, tex->GetID());
}

This is an overly simplified code from Quadron (similar to the DX9
approach), in reality it is much more complex as it supports multiple
rendertargets and so on.

2015-07-06 5:17 GMT+02:00 Nick Galko notifications@github.com:
