### ISSUE TITLE
Forward+ EarlyZ

### ISSUE THREAD

**Issue by galek** [asylum2010/Asylum_Tutorials#2]
Hi, it's again i'm :)

I not seen EarlyZ - Where it? - Forward+ must be with EarlyZ

**Comment by galek** [comment]
xm... you do earlyZ in lightaccum, but what contains zbuffer?(only sky texture)

**Comment by asylum2010** [comment]
layout(early_fragment_tests) in;

in _lightaccum.frag_

Z buffer is created along the color buffer:

framebuffer = new OpenGLFramebuffer(screenwidth, screenheight);
framebuffer->AttachTexture(GL_COLOR_ATTACHMENT0, GLFMT_A16B16G16R16F);
framebuffer->AttachTexture(GL_DEPTH_ATTACHMENT, GLFMT_D32F);

2015-08-21 4:35 GMT+02:00 Nick Galko notifications@github.com:

**Comment by galek** [comment]
ok,thanks
