### ISSUE TITLE
PBR Incorrect mul

### ISSUE THREAD

**Issue by galek** [asylum2010/Asylum_Tutorials#3]
I found this fragment by analyzing your and unity 5 shaders, after implementation in my engine:

Dot clamping ndotl and ndoth is incorrect, correct just dot.
See:
float ndotl = dot(n, l);
float ndoth = dot(n, h);

**Comment by asylum2010** [comment]
Derive why it's not needed, then I will believe it.

**Comment by galek** [comment]
This is a must see.
Unfortunately i can't take screenshots(incorrect work FBO).
But you can see shaders for this lighting-model in Unity5

http://netstorage.unity3d.com/unity/cc9cbbcc37b4/builtin_shaders-5.3.1f1.zip

**Comment by asylum2010** [comment]
Unity shaders are hardly PBR... Make a video of the problem then.

**Comment by galek** [comment]
Fixed, i found solution for problem - wrong coefficients

**Comment by asylum2010** [comment]
Again, this is not a Q&A helpdesk, so please spare me the bullshit next time.
