### ISSUE TITLE
Is needly check brdf.dds

### ISSUE THREAD

**Issue by galek** [asylum2010/Asylum_Tutorials#5]
Please, check this file. It corrupted(i can see this using any program. For example another brdf.dds files is fine(derkreature/IBLBaker for example))

**Comment by asylum2010** [comment]
No it's not corrupted at all, it's format is RG16F tho. You can view it with DxTex.
Also the code for it's generation can be found in 53_PrefilterEnvmap/main.cpp (#ifdef GENERATE_BRDF)
