### ISSUE TITLE
"Ocean" error

### ISSUE THREAD

**Issue by Mikez2015** [asylum2010/Asylum_Tutorials#6]
0(14) : error C1315: can't apply layout(rgba32f) to non-image
0(15) : error C1315: can't apply layout(rgba32f) to non-image

Videocard - Nvidia GT710

**Comment by asylum2010** [comment]
Thanks, this is one of many known issues affecting Nvidia and Intel cards. Will be fixed by the next merge (targeted for Q4).
In the meantime you can remove these errorneous layouts by hand.

**Comment by Mikez2015** [comment]
Thx, it's work.
